_smarthome/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("devices/", include("devices.urls")),
    path("", include("pages.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

devices/urls.py
from django.urls import path
from . import views

app_name = "devices"

urlpatterns = [
    path(
        "devices/",
        views.DeviceListView.as_view(),
        name="device_list",
    ),
    path(
        "cameras/",
        views.CameraListView.as_view(),
        name="camera_list",
    ),
    path(
        "cameras/<int:pk>",
        views.CameraDetailView.as_view(),
        name="camera_detail",
    ),
    path(
        "cameras/<int:pk>/update",
        views.CameraUpdateView.as_view(),
        name="camera_update",
    ),
    
]

pages/urls.py
from django.urls import path
from .views import IndexView

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
]

devices/models.py
from django.db import models
from django.urls import reverse


class Device(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        return self.camera.get_absolute_url()


class Camera(Device):
    device = models.OneToOneField(
        Device,
        on_delete=models.CASCADE,
        parent_link=True,
    )
    rtsp_url = models.CharField(max_length=200)
    privacy_mode = models.BooleanField(
        default=True,
    )
    tag_on = models.BooleanField(
        default=True,
    )

    def __str__(self):
        return f"{self.device}"

    def get_absolute_url(self):
        return reverse("devices:camera_detail", args=(self.pk,))

homes/models.py
from django.db import models

# Create your models here.

pages/models.py
from django.db import models


class Page(models.Model):
    title = models.CharField(
        max_length=200,
    )
    slug = models.SlugField(
        unique=True,
        null=True,
        blank=True,
    )

devices/forms.py
from django import forms

from devices import widgets
from . import models


class CameraForm(forms.ModelForm):
    take_photo = forms.BooleanField(
        disabled=True,
        widget=widgets.CheckboxToggleButtonWidget(
            attrs={"icon": "bi bi-camera"},
        ),
    )
    manual_recording = forms.BooleanField(
        disabled=True,
        widget=widgets.CheckboxToggleButtonWidget(
            attrs={
                "icon": "bi bi-camera-reels",
            },
        )
    )
    volume = forms.BooleanField(
        disabled=True,
        widget=widgets.CheckboxToggleButtonWidget(
            attrs={
                "icon": "bi bi-shield-lock",
            },
        )
    )
    voice_call = forms.BooleanField(
        disabled=True,
        widget=widgets.CheckboxToggleButtonWidget(
            attrs={
                "icon": "bi bi-volume-up",
            },
        )
    )
    talk = forms.BooleanField(
        disabled=True,
        widget=widgets.CheckboxToggleButtonWidget(
            attrs={
                "icon": "bi bi-telephone",
            },
        )
    )
    pan_tilt = forms.BooleanField(
        disabled=True,
        widget=widgets.CheckboxToggleButtonWidget(
            attrs={
                "icon": "bi bi-mic",
            },
        )
    )
    alarm_off = forms.BooleanField(
        disabled=True,
        widget=widgets.CheckboxToggleButtonWidget(
            attrs={
                "icon": "bi bi-arrows-move",
            },
        )
    )
    privacy_mode = forms.BooleanField(
        widget=widgets.CheckboxToggleButtonWidget(
            attrs={
                "icon": "bi bi-shield-lock",
            },
        )
    )
    tag_on = forms.BooleanField(
        widget=widgets.CheckboxToggleButtonWidget(
            attrs={
                "icon": "bi bi-person-bounding-box",
            },
        )
    )

    class Meta:
        model = models.Camera
        fields = "__all__"
        fields = (
            "take_photo",
            "manual_recording",
            "volume",
            "voice_call",
            "talk",
            "pan_tilt",
            "alarm_off",
            "privacy_mode",
            "tag_on",
        )

devices/views.py
from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic import CreateView
from django.views.generic import UpdateView

from devices.forms import CameraForm
from . import models


class DeviceListView(ListView):
    model = models.Device


class CameraListView(ListView):
    model = models.Camera


class CameraDetailView(DetailView):
    model = models.Camera

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = CameraForm(instance=self.object)
        return context


class CameraUpdateView(UpdateView):
    model = models.Camera
    fields = ("privacy_mode",)

    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        return super().form_valid(form)

homes/views.py
from django.shortcuts import render

# Create your views here.

pages/views.py
from django.views.generic import TemplateView

from devices.models import Device


class IndexView(TemplateView):
    template_name = "pages/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        devices = Device.objects.all()
        context["devices"] = devices
        return context

devices/templates/devices/camera_aside.html
<div id="kt_app_aside"
     class="app-aside flex-column mt-7"
     data-kt-drawer="true"
     data-kt-drawer-name="app-aside"
     data-kt-drawer-activate="{default: true, lg: false}"
     data-kt-drawer-overlay="true"
     data-kt-drawer-width="auto"
     data-kt-drawer-direction="end"
     data-kt-drawer-toggle="#kt_app_aside_toggle">
  <div id="kt_app_aside_wrapper"
       class="hover-scroll-y px-5 mx-5 my-5"
       data-kt-scroll="true"
       data-kt-scroll-activate="true"
       data-kt-scroll-height="auto"
       data-kt-scroll-dependencies="#kt_app_header"
       data-kt-scroll-wrappers="#kt_app_aside"
       data-kt-scroll-offset="5px"
       data-kt-scroll-save-state="true">
    <div class="card card-reset card-p-0">
      <div class="card-header align-items-center min-h-auto mb-7">
        <h3 class="card-title text-gray-900 fs-3 fw-bold py-0 mb-0">Shipment History</h3>
        <div class="card-toolbar mb-0">
          <a href="#"
             class="btn btn-sm btn-light"
             data-bs-toggle='tooltip'
             data-bs-dismiss='click'
             data-bs-custom-class="tooltip-inverse"
             title="Logistics App is coming soon">View All</a>
        </div>
      </div>
      <div class="card-body">
        <form method="post" action="{% url "devices:camera_update" object.pk %}">
          {% csrf_token %}
          <div class="row gy-5">
            {% for field in form %}
              <div class="col-6">
                {{ field }}
                <label for="{{ field.id_for_label }}" class="btn btn-light-primary ratio ratio-1x1">
                  <div class="d-flex flex-center flex-column gap-3">
                    <i class="{{ field.field.widget.attrs.icon }}"></i>
                    <small>{{ field.label }}</small>
                  </div>
                </label>
              </div>
            {% endfor %}
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

devices/templates/devices/camera_detail.html
{% extends "base.html" %}
{% block bodydata %}
  data-kt-app-aside-enabled="true"
  data-kt-app-aside-fixed="true"
  data-kt-app-aside-push-footer="true"
{% endblock bodydata %}
{% block content %}
  <div class="card card-flush h-100">
    <div class="card-header bg-black">
      <h3 class="card-title fw-bold text-white">Player</h3>
      <div class="card-toolbar"></div>
    </div>
    <div class="card-body bg-black pt-0">
      <div class="mb-6 text-center">
        <img src="/static/assets/media/svg/misc/video-play.svg"
             id="camera-feed"
             class="img-fluid" />
      </div>
      <div class="text-center mb-5">
        <h1 class="text-white fw-bold">Strange Friends</h1>
        <span class="text-white opacity-75 fw-semibold">Theresa Webb</span>
      </div>
    </div>
    <div class="card-footer bg-primary p-0 pb-9">
      <div class="mt-n10">
        <div class="mb-5">
          <div class="d-flex flex-stack px-4 text-white opacity-75">
            <span class="current-time" data-kt-element="current-time">0:00</span>
            <span class="duration" data-kt-element="duration">0:00</span>
          </div>
          <input type="range"
                 class="form-range"
                 data-kt-element="progress"
                 min="0"
                 max="100"
                 value="0"
                 step="0.01" />
        </div>
        <div class="d-flex flex-center">
          <button class="btn btn-icon mx-1" data-kt-element="replay-button">
            <i class="bi bi-arrow-repeat fs-2 text-white"></i>
          </button>
          <button class="btn btn-icon mx-1" data-kt-element="play-prev-button">
            <i class='bi bi-caret-left-fill fs-2 text-white'></i>
          </button>
          <button class="btn btn-icon mx-6 play-pause" data-kt-element="play-button">
            <i class="bi bi-play-fill text-white fs-4x" data-kt-element="play-icon"></i>
            <i class="bi bi-pause-fill text-white fs-4x d-none"
               data-kt-element="pause-icon"></i>
          </button>
          <button class="btn btn-icon mx-1 next" data-kt-element="play-next-button">
            <i class='bi bi-caret-right-fill fs-2 text-white'></i>
          </button>
          <button class="btn btn-icon mx-1" data-kt-element="shuffle-button">
            <i class="bi bi-shuffle fs-2 text-white"></i>
          </button>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}
{% block aside %}
  {% include "./camera_aside.html" %}
{% endblock aside %}
{% block js %}
{% if object.privacy_mode %}
<script>
  $(document).ready(function() {
    const pk = "{{ object.id }}"
    console.log(window.location.host)
    const ws = new WebSocket('wss:' + window.location.host + '/ws/camera-stream/' + pk + "/");
    
    ws.onmessage = function(event) {
      const data = JSON.parse(event.data); 
        $('#camera-feed').attr('src', 'data:image/jpeg;base64,' + data.jpg_as_text);
        
    };
});
</script>
{% endif %}
{% endblock js %}

devices/templates/devices/camera_form.html
{{ form }}

devices/templates/devices/camera_list.html
{% extends "base.html" %}
{% block content %}
  <div class="row g-5 g-xl-10 mb-5 mb-xl-10">
    <div class="col-xl-12">
      <div class="card card-flush h-xl-100">
        <div class="card-header pt-7">
          <h3 class="card-title align-items-start flex-column">
            <span class="card-label fw-bold text-gray-900">Recently Played</span>
            <span class="text-gray-500 mt-1 fw-semibold fs-6">Updated 37 minutes ago</span>
          </h3>
          <div class="card-toolbar">
            <a href="account/statements.html" class="btn btn-sm btn-light">History</a>
          </div>
        </div>
        <div class="card-body pt-7">
          <div class="row g-5 g-xl-9 mb-5 mb-xl-9">
            {% for camera in object_list %}
              <div class="col-sm-3 mb-3 mb-sm-0">
                <a href="{{ camera.get_absolute_url }}" class="m-0">
                  <div class="card-rounded position-relative mb-5">
                    <div class="bgi-position-center bgi-no-repeat bgi-size-cover h-200px card-rounded"
                         style="background-image:url('/static/assets/media/svg/misc/video-play.svg')"></div>
                    <button class="btn btn-icon h-auto w-auto p-0 ms-4 mb-4 position-absolute bottom-0 right-0"
                            data-kt-element="list-play-button">
                      <i class="bi bi-play-fill text-white fs-2x"
                         data-kt-element="list-play-icon"></i>
                      <i class="bi bi-pause-fill text-white fs-2x d-none"
                         data-kt-element="list-pause-icon"></i>
                    </button>
                  </div>
                  <div class="m-0">
                    <span class="text-gray-800 text-hover-primary fs-3 fw-bold d-block mb-2">{{ camera }}</span>
                  </div>
                </a>
              </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

devices/templates/devices/forms/widgets/checkbox_toggle_button.html
<input type="{{ widget.type }}"
       {% comment %} class="btn-check" {% endcomment %}
       name="{{ widget.name }}"
       id="{{ widget.name }}"
       onchange="this.form.submit()"
       value="{{ widget.value }}"
       {% if widget.disabled %}disabled{% endif %}
       {% if widget.required %}required{% endif %}
       {% if widget.value %}checked{% endif %}/>

pages/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
      {% block title %}
        {{ object }}
      {% endblock title %}
    </title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <link href="{% static "assets/plugins/global/plugins.bundle.css" %}"
          rel="stylesheet"
          type="text/css" />
    <link href="{% static "assets/css/style.bundle.css" %}"
          rel="stylesheet"
          type="text/css" />
  </head>
  <body id="kt_app_body"
        data-kt-app-layout="dark-sidebar"
        data-kt-app-header-fixed="true"
        data-kt-app-sidebar-enabled="true"
        data-kt-app-sidebar-fixed="true"
        data-kt-app-sidebar-hoverable="true"
        data-kt-app-sidebar-push-header="true"
        data-kt-app-sidebar-push-toolbar="true"
        data-kt-app-sidebar-push-footer="true"
        data-kt-app-toolbar-enabled="true"
        {% block bodydata %}
        {% endblock bodydata %}
        class="app-default">
    {% include "theme_mode.html" %}
    <div class="d-flex flex-column flex-root app-root" id="kt_app_root">
      <div class="app-page flex-column flex-column-fluid" id="kt_app_page">
        {% block header %}
          {% include "header.html" %}
        {% endblock header %}
        <div class="app-wrapper flex-column flex-row-fluid" id="kt_app_wrapper">
          {% block sidebar %}
            {% include "sidebar.html" %}
          {% endblock sidebar %}
          <div class="app-main flex-column flex-row-fluid" id="kt_app_main">
            <div class="d-flex flex-column flex-column-fluid">
              {% block toolbar %}
                {% include "toolbar.html" %}
              {% endblock toolbar %}
              <div id="kt_app_content" class="app-content flex-column-fluid">
                <div id="kt_app_content_container" class="app-container container-fluid">
                  {% block content %}
                  {% endblock content %}
                </div>
              </div>
            </div>
            {% block footer %}
              {% include "footer.html" %}
            {% endblock footer %}
          </div>
          {% block aside %}
          {% endblock aside %}
        </div>
      </div>
    </div>
    {% include "scrolltop.html" %}
    <script src="{% static "assets/plugins/global/plugins.bundle.js" %}"></script>
    <script src="{% static "assets/js/scripts.bundle.js" %}"></script>
    {% block js %}
    {% endblock js %}
  </body>
</html>

pages/templates/footer.html
<div id="kt_app_footer" class="app-footer">
    <!--begin::Footer container-->
    <div class="app-container container-fluid d-flex flex-column flex-md-row flex-center flex-md-stack py-3">
        <!--begin::Copyright-->
        <div class="text-gray-900 order-2 order-md-1">
            <span class="text-muted fw-semibold me-1">2024&copy;</span>
            <a href="https://keenthemes.com" target="_blank" class="text-gray-800 text-hover-primary">Keenthemes</a>
        </div>
        <!--end::Copyright-->
        <!--begin::Menu-->
        <ul class="menu menu-gray-600 menu-hover-primary fw-semibold order-1">
            <li class="menu-item">
                <a href="https://keenthemes.com" target="_blank" class="menu-link px-2">About</a>
            </li>
            <li class="menu-item">
                <a href="https://devs.keenthemes.com" target="_blank" class="menu-link px-2">Support</a>
            </li>
            <li class="menu-item">
                <a href="https://1.envato.market/Vm7VRE" target="_blank" class="menu-link px-2">Purchase</a>
            </li>
        </ul>
        <!--end::Menu-->
    </div>
    <!--end::Footer container-->
</div>

pages/templates/header.html
<div id="kt_app_header"
     class="app-header"
     data-kt-sticky="true"
     data-kt-sticky-activate="{default: true, lg: true}"
     data-kt-sticky-name="app-header-minimize"
     data-kt-sticky-offset="{default: '200px', lg: '0'}"
     data-kt-sticky-animation="false">
  <div class="app-container container-fluid d-flex align-items-stretch justify-content-between"
       id="kt_app_header_container">
    <div class="d-flex align-items-center d-lg-none ms-n3 me-1 me-md-2"
         title="Show sidebar menu">
      <div class="btn btn-icon btn-active-color-primary w-35px h-35px"
           id="kt_app_sidebar_mobile_toggle">
        <i class="ki-duotone ki-abstract-14 fs-2 fs-md-1">
          <span class="path1"></span>
          <span class="path2"></span>
        </i>
      </div>
    </div>
    <div class="d-flex align-items-center flex-grow-1 flex-lg-grow-0">
      <a href="index.html" class="d-lg-none">
        <img alt="Logo"
             src="{% get_static_prefix %}assets/media/logos/default-small.svg"
             class="h-30px" />
      </a>
    </div>
    <div class="d-flex align-items-stretch justify-content-between flex-lg-grow-1"
         id="kt_app_header_wrapper">
      <div class="app-header-menu app-header-mobile-drawer align-items-stretch"
           data-kt-drawer="true"
           data-kt-drawer-name="app-header-menu"
           data-kt-drawer-activate="{default: true, lg: false}"
           data-kt-drawer-overlay="true"
           data-kt-drawer-width="250px"
           data-kt-drawer-direction="end"
           data-kt-drawer-toggle="#kt_app_header_menu_toggle"
           data-kt-swapper="true"
           data-kt-swapper-mode="{default: 'append', lg: 'prepend'}"
           data-kt-swapper-parent="{default: '#kt_app_body', lg: '#kt_app_header_wrapper'}"></div>
      <div class="app-navbar flex-shrink-0">
        <div class="app-navbar-item ms-1 ms-md-4">
          <a href="#"
             class="btn btn-icon btn-custom btn-icon-muted btn-active-light btn-active-color-primary w-35px h-35px"
             data-kt-menu-trigger="{default:'click', lg: 'hover'}"
             data-kt-menu-attach="parent"
             data-kt-menu-placement="bottom-end">
            <i class="ki-duotone ki-night-day theme-light-show fs-1">
              <span class="path1"></span>
              <span class="path2"></span>
              <span class="path3"></span>
              <span class="path4"></span>
              <span class="path5"></span>
              <span class="path6"></span>
              <span class="path7"></span>
              <span class="path8"></span>
              <span class="path9"></span>
              <span class="path10"></span>
            </i>
            <i class="ki-duotone ki-moon theme-dark-show fs-1">
              <span class="path1"></span>
              <span class="path2"></span>
            </i>
          </a>
          <div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-title-gray-700 menu-icon-gray-500 menu-active-bg menu-state-color fw-semibold py-4 fs-base w-150px"
               data-kt-menu="true"
               data-kt-element="theme-mode-menu">
            <div class="menu-item px-3 my-0">
              <a href="#"
                 class="menu-link px-3 py-2"
                 data-kt-element="mode"
                 data-kt-value="light">
                <span class="menu-icon" data-kt-element="icon">
                  <i class="ki-duotone ki-night-day fs-2">
                    <span class="path1"></span>
                    <span class="path2"></span>
                    <span class="path3"></span>
                    <span class="path4"></span>
                    <span class="path5"></span>
                    <span class="path6"></span>
                    <span class="path7"></span>
                    <span class="path8"></span>
                    <span class="path9"></span>
                    <span class="path10"></span>
                  </i>
                </span>
                <span class="menu-title">Light</span>
              </a>
            </div>
            <div class="menu-item px-3 my-0">
              <a href="#"
                 class="menu-link px-3 py-2"
                 data-kt-element="mode"
                 data-kt-value="dark">
                <span class="menu-icon" data-kt-element="icon">
                  <i class="ki-duotone ki-moon fs-2">
                    <span class="path1"></span>
                    <span class="path2"></span>
                  </i>
                </span>
                <span class="menu-title">Dark</span>
              </a>
            </div>
            <div class="menu-item px-3 my-0">
              <a href="#"
                 class="menu-link px-3 py-2"
                 data-kt-element="mode"
                 data-kt-value="system">
                <span class="menu-icon" data-kt-element="icon">
                  <i class="ki-duotone ki-screen fs-2">
                    <span class="path1"></span>
                    <span class="path2"></span>
                    <span class="path3"></span>
                    <span class="path4"></span>
                  </i>
                </span>
                <span class="menu-title">System</span>
              </a>
            </div>
          </div>
        </div>
        <div class="app-navbar-item ms-1 ms-md-4" id="kt_header_user_menu_toggle">
          <div class="cursor-pointer symbol symbol-35px"
               data-kt-menu-trigger="{default: 'click', lg: 'hover'}"
               data-kt-menu-attach="parent"
               data-kt-menu-placement="bottom-end">
            <img src="{% get_static_prefix %}assets/media/avatars/300-3.jpg"
                 class="rounded-3"
                 alt="user" />
          </div>
          <div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-800 menu-state-bg menu-state-color fw-semibold py-4 fs-6 w-275px"
               data-kt-menu="true">
            <div class="menu-item px-3">
              <div class="menu-content d-flex align-items-center px-3">
                <div class="symbol symbol-50px me-5">
                  <img alt="Logo"
                       src="{% get_static_prefix %}assets/media/avatars/300-3.jpg" />
                </div>
                <div class="d-flex flex-column">
                  <div class="fw-bold d-flex align-items-center fs-5">
                    Robert Fox
                    <span class="badge badge-light-success fw-bold fs-8 px-2 py-1 ms-2">Pro</span>
                  </div>
                  <a href="#" class="fw-semibold text-muted text-hover-primary fs-7">robert@kt.com</a>
                </div>
              </div>
            </div>
            <div class="menu-item px-5">
              <a href="authentication/layouts/corporate/sign-in.html"
                 class="menu-link px-5">Sign Out</a>
            </div>
          </div>
        </div>
        <div class="app-navbar-item d-lg-none ms-2 me-n2" title="Show header menu">
          <div class="btn btn-flex btn-icon btn-active-color-primary w-30px h-30px"
               id="kt_app_header_menu_toggle">
            <i class="ki-duotone ki-element-4 fs-1">
              <span class="path1"></span>
              <span class="path2"></span>
            </i>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

pages/templates/pages/index.html
{% extends "base.html" %}
{% block content %}
  <div class="row row-cols-4 gy-7">
    {% for device in devices %}
      <div class="col">
        <a href="{{ device.get_absolute_url }}" class="card card-flush">
          <div class="card-header">
            <div class="card-title">
              <div class="symbol">
                <img src="/static/assets/media/misc/image.png" />
              </div>
            </div>
            <div class="card-toolbar">
              <button type="button" class="btn btn-sm btn-light">Offline</button>
            </div>
          </div>
          <div class="card-body text-center fw-bold">{{ device }}</div>
        </a>
      </div>
    {% endfor %}
  </div>
{% endblock content %}

pages/templates/scrolltop.html
<div id="kt_scrolltop" class="scrolltop" data-kt-scrolltop="true">
    <i class="ki-duotone ki-arrow-up">
        <span class="path1"></span>
        <span class="path2"></span>
    </i>
</div>

pages/templates/sidebar.html
<div id="kt_app_sidebar"
     class="app-sidebar flex-column"
     data-kt-drawer="true"
     data-kt-drawer-name="app-sidebar"
     data-kt-drawer-activate="{default: true, lg: false}"
     data-kt-drawer-overlay="true"
     data-kt-drawer-width="225px"
     data-kt-drawer-direction="start"
     data-kt-drawer-toggle="#kt_app_sidebar_mobile_toggle">
  <div class="app-sidebar-logo px-6" id="kt_app_sidebar_logo">
    <a href="index.html">
      <img alt="Logo"
           src="/static/assets/media/logos/default-dark.svg"
           class="h-25px app-sidebar-logo-default" />
      <img alt="Logo"
           src="/static/assets/media/logos/default-small.svg"
           class="h-20px app-sidebar-logo-minimize" />
    </a>
    <div id="kt_app_sidebar_toggle"
         class="app-sidebar-toggle btn btn-icon btn-shadow btn-sm btn-color-muted btn-active-color-primary h-30px w-30px position-absolute top-50 start-100 translate-middle rotate"
         data-kt-toggle="true"
         data-kt-toggle-state="active"
         data-kt-toggle-target="body"
         data-kt-toggle-name="app-sidebar-minimize">
      <i class="ki-duotone ki-black-left-line fs-3 rotate-180">
        <span class="path1"></span>
        <span class="path2"></span>
      </i>
    </div>
  </div>
  <div class="app-sidebar-menu overflow-hidden flex-column-fluid">
    <div id="kt_app_sidebar_menu_wrapper" class="app-sidebar-wrapper">
      <div id="kt_app_sidebar_menu_scroll"
           class="scroll-y my-5 mx-3"
           data-kt-scroll="true"
           data-kt-scroll-activate="true"
           data-kt-scroll-height="auto"
           data-kt-scroll-dependencies="#kt_app_sidebar_logo, #kt_app_sidebar_footer"
           data-kt-scroll-wrappers="#kt_app_sidebar_menu"
           data-kt-scroll-offset="5px"
           data-kt-scroll-save-state="true">
        <div class="menu menu-column menu-rounded menu-sub-indention fw-semibold fs-6"
             id="#kt_app_sidebar_menu"
             data-kt-menu="true"
             data-kt-menu-expand="false">
          <div data-kt-menu-trigger="click"
               class="menu-item here show menu-accordion">
            <a href="/" class="menu-link">
              <span class="menu-icon">
                <i class="bi bi-house-fill fs-2"></i>
              </span>
              <span class="menu-title">{% trans "Home" %}</span>
            </a>
          </div>
          <div data-kt-menu-trigger="click"
               class="menu-item here show menu-accordion">
            <a href="{% url "devices:camera_list" %}" class="menu-link">
              <span class="menu-icon">
                <i class="bi bi-camera-reels-fill fs-2"></i>
              </span>
              <span class="menu-title">{% trans "Cameras" %}</span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="app-sidebar-footer flex-column-auto pt-2 pb-6 px-6"
       id="kt_app_sidebar_footer">
    <a href="https://preview.keenthemes.com/html/metronic/docs"
       class="btn btn-flex flex-center btn-custom btn-primary overflow-hidden text-nowrap px-0 h-40px w-100"
       data-bs-toggle="tooltip"
       data-bs-trigger="hover"
       data-bs-dismiss-="click"
       title="200+ in-house components and 3rd-party plugins">
      <span class="btn-label">Docs & Components</span>
      <i class="ki-duotone ki-document btn-icon fs-2 m-0">
        <span class="path1"></span>
        <span class="path2"></span>
      </i>
    </a>
  </div>
</div>

pages/templates/theme_mode.html
<script>var defaultThemeMode = "light"; var themeMode; if ( document.documentElement ) { if ( document.documentElement.hasAttribute("data-bs-theme-mode")) { themeMode = document.documentElement.getAttribute("data-bs-theme-mode"); } else { if ( localStorage.getItem("data-bs-theme") !== null ) { themeMode = localStorage.getItem("data-bs-theme"); } else { themeMode = defaultThemeMode; } } if (themeMode === "system") { themeMode = window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light"; } document.documentElement.setAttribute("data-bs-theme", themeMode); }</script>

pages/templates/toolbar.html
<div id="kt_app_toolbar" class="app-toolbar py-3 py-lg-6">
  <div id="kt_app_toolbar_container"
       class="app-container container-fluid d-flex flex-stack">
    <div class="page-title d-flex flex-column justify-content-center flex-wrap me-3">
      <h1 class="page-heading d-flex text-gray-900 fw-bold fs-3 flex-column justify-content-center my-0">
        {% trans "Home" %}
      </h1>
      {% comment %} <ul class="breadcrumb breadcrumb-separatorless fw-semibold fs-7 my-0 pt-1">
                <li class="breadcrumb-item text-muted">
                    <a href="index.html" class="text-muted text-hover-primary">Home</a>
                </li>
                <li class="breadcrumb-item">
                    <span class="bullet bg-gray-500 w-5px h-2px"></span>
                </li>
                <li class="breadcrumb-item text-muted">Dashboards</li>
      </ul> {% endcomment %}
    </div>
    <div class="d-flex align-items-center gap-2 gap-lg-3">
      <a href="#" class="btn btn-sm fw-bold btn-primary">{% trans "Add" %}</a>
    </div>
  </div>
</div>